[project]
name = "harmony-flow"
description = "NASA Harmony API Service for creating vector flow textures"
authors = [
    {name="Jacqueline Ryan", email="Jacqueline.Ryan@jpl.nasa.gov"},
]
maintainers = [
    {name="Jacqueline Ryan", email="Jacqueline.Ryan@jpl.nasa.gov"},
]
readme = "README.md"
license = { text = "Apache-2.0" }
requires-python = ">=3.12, <4"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
]
dynamic = ["version"]
dependencies = [
    "cftime ~= 1.6",
    "dask ~= 2026.3.0",
    "h5netcdf ~= 1.8",
    "h5py ~= 3.16",
    "harmony-service-lib ~= 2.11.0",
    "icechunk ~= 1.1",
    "obstore ~= 0.9",
    "rasterio ~= 1.5",
    "requests ~= 2.33",
    "virtualizarr ~= 2.5",
]

[project.urls]
Homepage = "https://github.com/jackiryan/harmony-flow-py"
Issues = "https://github.com/jackiryan/harmony-flow-py/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "docker/service_version.txt"
pattern = "(?P<version>[\\w.-]+)"

[tool.hatch.build.targets.wheel]
packages = ["src/harmony_flow"]

[dependency-groups]
dev = [
    "coverage ~= 7.13",
    "earthaccess ~= 0.17",
    "ruff ~= 0.15",
    "mypy ~= 1.20",
    "pre-commit ~= 4.6",
    "pytest ~= 9.0",
    "pytest-cov ~= 7.1.0",
    "types-requests ~= 2.33",
]

[tool.ruff]
line-length = 99

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = ["F401"]

[tool.mypy]
mypy_path = ["src", "tests"]

[[tool.mypy.overrides]]
module = ["harmony_service_lib.*", "h5py", "h5netcdf", "rasterio.*"]
ignore_missing_imports = true